# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MainPage(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1039, 913)
        MainWindow.setStyleSheet("background-color:rgb(231,231,231);color:rgb(236,236,236);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 640, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(0,0,0);background-color:rgb(236,236,236);")
        self.label_2.setObjectName("label_2")
        self.comboBoxCarCount = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxCarCount.setGeometry(QtCore.QRect(120, 640, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBoxCarCount.setFont(font)
        self.comboBoxCarCount.setStyleSheet("QComboBox{\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray; \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(236,236,236);   \n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: rgb(236,236,236);\n"
"    background-color: rgb(20, 136, 208); \n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxCarCount.setObjectName("comboBoxCarCount")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 640, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(0,0,0);background-color:rgb(236,236,236);")
        self.label_3.setObjectName("label_3")
        self.comboBoxRoadType = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxRoadType.setGeometry(QtCore.QRect(330, 640, 131, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBoxRoadType.setFont(font)
        self.comboBoxRoadType.setStyleSheet("QComboBox{\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray; \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(236,236,236);    \n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: rgb(236,236,236);\n"
"    background-color: rgb(20, 136, 208); \n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxRoadType.setObjectName("comboBoxRoadType")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 740, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(0,0,0);background-color:rgb(236,236,236);")
        self.label_4.setObjectName("label_4")
        self.comboBoxV1Direction = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxV1Direction.setGeometry(QtCore.QRect(150, 740, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBoxV1Direction.setFont(font)
        self.comboBoxV1Direction.setStyleSheet("QComboBox{\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray; \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(236,236,236);    \n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: rgb(236,236,236);\n"
"    background-color: rgb(20, 136, 208); \n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxV1Direction.setObjectName("comboBoxV1Direction")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 740, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(0,0,0);background-color:rgb(236,236,236);")
        self.label_5.setObjectName("label_5")
        self.comboBoxV1Lane = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxV1Lane.setGeometry(QtCore.QRect(330, 740, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBoxV1Lane.setFont(font)
        self.comboBoxV1Lane.setStyleSheet("QComboBox{\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray; \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(236,236,236);     \n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: rgb(236,236,236);\n"
"    background-color: rgb(20, 136, 208); \n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxV1Lane.setObjectName("comboBoxV1Lane")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(480, 640, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(0, 0, 0);background-color:rgb(236,236,236);")
        self.label_8.setObjectName("label_8")
        self.comboBoxLaneCount = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxLaneCount.setGeometry(QtCore.QRect(580, 640, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBoxLaneCount.setFont(font)
        self.comboBoxLaneCount.setStyleSheet("QComboBox{\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray; \n"
"    color: rgb(0, 0, 0);\n"
"   background-color: rgb(236,236,236);    \n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: rgb(236,236,236);\n"
"    background-color: rgb(20, 136, 208); \n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxLaneCount.setObjectName("comboBoxLaneCount")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(410, 740, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(0,0,0);background-color:rgb(236,236,236);")
        self.label_9.setObjectName("label_9")
        self.comboBoxV1Action = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxV1Action.setGeometry(QtCore.QRect(500, 740, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBoxV1Action.setFont(font)
        self.comboBoxV1Action.setStyleSheet("QComboBox{\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray; \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(236,236,236);    \n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: rgb(236,236,236);\n"
"    background-color: rgb(20, 136, 208); \n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxV1Action.setObjectName("comboBoxV1Action")
        self.comboBoxV1TargetLane = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxV1TargetLane.setGeometry(QtCore.QRect(770, 740, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBoxV1TargetLane.setFont(font)
        self.comboBoxV1TargetLane.setStyleSheet("QComboBox{\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray; \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(236,236,236);     \n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: rgb(236,236,236);\n"
"    background-color: rgb(20, 136, 208); \n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxV1TargetLane.setObjectName("comboBoxV1TargetLane")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(640, 740, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgb(0,0,0);background-color:rgb(236,236,236);")
        self.label_10.setObjectName("label_10")
        self.comboBoxV2Lane = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxV2Lane.setGeometry(QtCore.QRect(330, 790, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBoxV2Lane.setFont(font)
        self.comboBoxV2Lane.setStyleSheet("QComboBox{\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray; \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(236,236,236);  \n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: rgb(236,236,236);\n"
"    background-color: rgb(20, 136, 208); \n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxV2Lane.setObjectName("comboBoxV2Lane")
        self.comboBoxV2TargetLane = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxV2TargetLane.setGeometry(QtCore.QRect(770, 790, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBoxV2TargetLane.setFont(font)
        self.comboBoxV2TargetLane.setStyleSheet("QComboBox{\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray; \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(236,236,236);  \n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: rgb(236,236,236);\n"
"    background-color: rgb(20, 136, 208); \n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxV2TargetLane.setObjectName("comboBoxV2TargetLane")
        self.comboBoxV2Action = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxV2Action.setGeometry(QtCore.QRect(500, 790, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBoxV2Action.setFont(font)
        self.comboBoxV2Action.setStyleSheet("QComboBox{\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray; \n"
"    color: rgb(0, 0, 0);\n"
"   background-color: rgb(236,236,236);  \n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: rgb(236,236,236);\n"
"    background-color: rgb(20, 136, 208); \n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxV2Action.setObjectName("comboBoxV2Action")
        self.labelV2Lane = QtWidgets.QLabel(self.centralwidget)
        self.labelV2Lane.setGeometry(QtCore.QRect(250, 790, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelV2Lane.setFont(font)
        self.labelV2Lane.setStyleSheet("color:rgb(0,0,0);background-color:rgb(236,236,236);")
        self.labelV2Lane.setObjectName("labelV2Lane")
        self.labelV2TargetLane = QtWidgets.QLabel(self.centralwidget)
        self.labelV2TargetLane.setGeometry(QtCore.QRect(640, 790, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelV2TargetLane.setFont(font)
        self.labelV2TargetLane.setStyleSheet("color:rgb(0,0,0);background-color:rgb(236,236,236);")
        self.labelV2TargetLane.setObjectName("labelV2TargetLane")
        self.labelV2Direction = QtWidgets.QLabel(self.centralwidget)
        self.labelV2Direction.setGeometry(QtCore.QRect(30, 790, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelV2Direction.setFont(font)
        self.labelV2Direction.setStyleSheet("color:rgb(0,0,0);background-color:rgb(236,236,236);")
        self.labelV2Direction.setObjectName("labelV2Direction")
        self.labelV2Action = QtWidgets.QLabel(self.centralwidget)
        self.labelV2Action.setGeometry(QtCore.QRect(410, 790, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelV2Action.setFont(font)
        self.labelV2Action.setStyleSheet("color:rgb(0,0,0);background-color:rgb(236,236,236);")
        self.labelV2Action.setObjectName("labelV2Action")
        self.comboBoxV2Direction = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxV2Direction.setGeometry(QtCore.QRect(150, 790, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBoxV2Direction.setFont(font)
        self.comboBoxV2Direction.setStyleSheet("QComboBox{\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray; \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(236,236,236);   \n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: rgb(236,236,236);\n"
"    background-color: rgb(20, 136, 208); \n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxV2Direction.setObjectName("comboBoxV2Direction")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(850, 740, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:rgb(0,0,0);background-color:rgb(236,236,236);")
        self.label_11.setObjectName("label_11")
        self.labelV2Speed = QtWidgets.QLabel(self.centralwidget)
        self.labelV2Speed.setGeometry(QtCore.QRect(850, 790, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelV2Speed.setFont(font)
        self.labelV2Speed.setStyleSheet("color:rgb(0,0,0);background-color:rgb(236,236,236);")
        self.labelV2Speed.setObjectName("labelV2Speed")
        self.spinBoxV2Speed = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxV2Speed.setGeometry(QtCore.QRect(940, 790, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.spinBoxV2Speed.setFont(font)
        self.spinBoxV2Speed.setStyleSheet("    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"\n"
"\n"
"")
        self.spinBoxV2Speed.setMinimum(1)
        self.spinBoxV2Speed.setMaximum(100)
        self.spinBoxV2Speed.setProperty("value", 20)
        self.spinBoxV2Speed.setObjectName("spinBoxV2Speed")
        self.spinBoxV1Speed = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxV1Speed.setGeometry(QtCore.QRect(940, 740, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.spinBoxV1Speed.setFont(font)
        self.spinBoxV1Speed.setStyleSheet("\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"\n"
"\n"
"")
        self.spinBoxV1Speed.setMinimum(1)
        self.spinBoxV1Speed.setMaximum(100)
        self.spinBoxV1Speed.setProperty("value", 20)
        self.spinBoxV1Speed.setObjectName("spinBoxV1Speed")
        self.textBrowserWaypoint = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowserWaypoint.setGeometry(QtCore.QRect(20, 340, 411, 241))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.textBrowserWaypoint.setFont(font)
        self.textBrowserWaypoint.setStyleSheet("background-color:rgb(236,236,236);\n"
"border:1px solid rgb(190, 190, 190);\n"
"color:rgb(0,0,0)")
        self.textBrowserWaypoint.setObjectName("textBrowserWaypoint")
        self.comboBoxEgo = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxEgo.setGeometry(QtCore.QRect(330, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBoxEgo.setFont(font)
        self.comboBoxEgo.setStyleSheet("QComboBox{\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray; \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(236,236,236);  \n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: rgb(236,236,236);\n"
"    background-color: rgb(20, 136, 208); \n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxEgo.setObjectName("comboBoxEgo")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(270, 300, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:rgb(0,0,0);background-color:rgb(231,231,231);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(700, 640, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:rgb(0,0,0);background-color:rgb(236,236,236);")
        self.label_13.setObjectName("label_13")
        self.comboBoxWeather = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxWeather.setGeometry(QtCore.QRect(866, 640, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBoxWeather.setFont(font)
        self.comboBoxWeather.setStyleSheet("QComboBox{\n"
"    background-color:rgb(231,231,231);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray; \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(236,236,236);    \n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: rgb(236,236,236);\n"
"    background-color: rgb(20, 136, 208); \n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxWeather.setObjectName("comboBoxWeather")
        self.lineEditWeather = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditWeather.setGeometry(QtCore.QRect(790, 640, 201, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lineEditWeather.setFont(font)
        self.lineEditWeather.setStyleSheet("\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lineEditWeather.setObjectName("lineEditWeather")
        self.comboBoxImpactPart = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxImpactPart.setGeometry(QtCore.QRect(330, 690, 131, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBoxImpactPart.setFont(font)
        self.comboBoxImpactPart.setStyleSheet("QComboBox{\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray; \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(236,236,236);    \n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: rgb(236,236,236);\n"
"    background-color: rgb(20, 136, 208); \n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxImpactPart.setObjectName("comboBoxImpactPart")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 690, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(0,0,0);background-color:rgb(236,236,236);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(230, 690, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(0,0,0);background-color:rgb(236,236,236);")
        self.label_7.setObjectName("label_7")
        self.comboBoxStriker = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxStriker.setGeometry(QtCore.QRect(120, 690, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBoxStriker.setFont(font)
        self.comboBoxStriker.setStyleSheet("QComboBox{\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray; \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(236,236,236);   \n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: rgb(236,236,236);\n"
"    background-color: rgb(20, 136, 208); \n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxStriker.setObjectName("comboBoxStriker")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:rgb(20, 136, 208);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(450, 10, 491, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color:rgb(20, 136, 208);")
        self.label_15.setObjectName("label_15")
        self.barWidget = QtWidgets.QWidget(self.centralwidget)
        self.barWidget.setGeometry(QtCore.QRect(450, 50, 571, 531))
        self.barWidget.setStyleSheet("background-color:rgb(236,236,236);\n"
"border:1px solid rgb(190, 190, 190);")
        self.barWidget.setObjectName("barWidget")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(20, 590, 341, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color:rgb(20, 136, 208);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(20, 300, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color:rgb(20, 136, 208);")
        self.label_17.setObjectName("label_17")
        self.textBrowserInfo = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowserInfo.setGeometry(QtCore.QRect(20, 50, 411, 241))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.textBrowserInfo.setFont(font)
        self.textBrowserInfo.setStyleSheet("background-color:rgb(236,236,236);\n"
"border:1px solid rgb(190, 190, 190);\n"
"color:rgb(0,0,0)")
        self.textBrowserInfo.setObjectName("textBrowserInfo")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 630, 1001, 201))
        self.widget.setStyleSheet("background-color:rgb(236,236,236);\n"
"border:1px solid rgb(190, 190, 190);")
        self.widget.setObjectName("widget")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(480, 590, 261, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color:rgb(0,0,0);background-color:rgb(231,231,231);")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(300, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:rgb(0,0,0);background-color:rgb(231,231,231);")
        self.label_19.setObjectName("label_19")
        self.checkBoxAddToGenerate = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxAddToGenerate.setGeometry(QtCore.QRect(450, 590, 21, 31))
        self.checkBoxAddToGenerate.setStyleSheet("color:rgb(20, 136, 208)")
        self.checkBoxAddToGenerate.setText("")
        self.checkBoxAddToGenerate.setObjectName("checkBoxAddToGenerate")
        self.checkBoxAddToRecord = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxAddToRecord.setGeometry(QtCore.QRect(270, 10, 21, 31))
        self.checkBoxAddToRecord.setStyleSheet("color:rgb(20, 136, 208)")
        self.checkBoxAddToRecord.setText("")
        self.checkBoxAddToRecord.setObjectName("checkBoxAddToRecord")
        self.labelCopyInfoGPT = QtWidgets.QLabel(self.centralwidget)
        self.labelCopyInfoGPT.setGeometry(QtCore.QRect(210, 4, 41, 41))
        self.labelCopyInfoGPT.setText("")
        self.labelCopyInfoGPT.setObjectName("labelCopyInfoGPT")
        self.labelCopyWaypoint = QtWidgets.QLabel(self.centralwidget)
        self.labelCopyWaypoint.setGeometry(QtCore.QRect(170, 300, 41, 31))
        self.labelCopyWaypoint.setText("")
        self.labelCopyWaypoint.setObjectName("labelCopyWaypoint")
        self.labelCopyInfoGT = QtWidgets.QLabel(self.centralwidget)
        self.labelCopyInfoGT.setGeometry(QtCore.QRect(370, 590, 41, 31))
        self.labelCopyInfoGT.setText("")
        self.labelCopyInfoGT.setObjectName("labelCopyInfoGT")
        self.labelCopyRate = QtWidgets.QLabel(self.centralwidget)
        self.labelCopyRate.setGeometry(QtCore.QRect(950, 10, 41, 31))
        self.labelCopyRate.setText("")
        self.labelCopyRate.setObjectName("labelCopyRate")
        self.widget.raise_()
        self.label_2.raise_()
        self.comboBoxCarCount.raise_()
        self.label_3.raise_()
        self.comboBoxRoadType.raise_()
        self.label_4.raise_()
        self.comboBoxV1Direction.raise_()
        self.label_5.raise_()
        self.comboBoxV1Lane.raise_()
        self.label_8.raise_()
        self.comboBoxLaneCount.raise_()
        self.label_9.raise_()
        self.comboBoxV1Action.raise_()
        self.comboBoxV1TargetLane.raise_()
        self.label_10.raise_()
        self.comboBoxV2Lane.raise_()
        self.comboBoxV2TargetLane.raise_()
        self.comboBoxV2Action.raise_()
        self.labelV2Lane.raise_()
        self.labelV2TargetLane.raise_()
        self.labelV2Direction.raise_()
        self.labelV2Action.raise_()
        self.comboBoxV2Direction.raise_()
        self.label_11.raise_()
        self.labelV2Speed.raise_()
        self.spinBoxV2Speed.raise_()
        self.spinBoxV1Speed.raise_()
        self.textBrowserWaypoint.raise_()
        self.comboBoxEgo.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.comboBoxWeather.raise_()
        self.lineEditWeather.raise_()
        self.comboBoxImpactPart.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.comboBoxStriker.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.barWidget.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.textBrowserInfo.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.checkBoxAddToGenerate.raise_()
        self.checkBoxAddToRecord.raise_()
        self.labelCopyInfoGPT.raise_()
        self.labelCopyWaypoint.raise_()
        self.labelCopyInfoGT.raise_()
        self.labelCopyRate.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1039, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("QMenuBar{\n"
"    background-color:rgb(125,182,191);\n"
"    border:none;\n"
"\n"
"}\n"
"QMenuBar::item{\n"
"    color:white;\n"
"    padding:10px;\n"
"}\n"
"QMenuBar::item:selected{\n"
"    background-color: rgb(20, 136, 208);\n"
"}\n"
"QMenuBar::item:pressed{\n"
"    background-color: rgb(20, 136, 208);\n"
"}")
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.menu_F.setFont(font)
        self.menu_F.setStyleSheet("QMenu{\n"
"    background-color: rgb(236,236,236);  \n"
"    border:1px solid rgb(190, 190, 190);\n"
"}\n"
"QMenu::item{\n"
"    color:rgb(0,0,0)\n"
"}\n"
"QMenu::selected{\n"
"    background-color:  rgb(20, 136, 208);\n"
"}\n"
"QMenu::pressed{\n"
"    background-color:  rgb(20, 136, 208);\n"
"}\n"
"\n"
"")
        self.menu_F.setObjectName("menu_F")
        self.menu_S_2 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.menu_S_2.setFont(font)
        self.menu_S_2.setStyleSheet("QMenu{\n"
"    background-color: rgb(236,236,236);  \n"
"    border:1px solid rgb(190, 190, 190)\n"
"}\n"
"QMenu::item{\n"
"    color:rgb(0,0,0);\n"
"}\n"
"QMenu::selected{\n"
"    background-color:  rgb(20, 136, 208);\n"
"}\n"
"QMenu::pressed{\n"
"    background-color:  rgb(20, 136, 208);\n"
"}\n"
"\n"
"")
        self.menu_S_2.setObjectName("menu_S_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("background-color:rgb(125,182,191);\n"
"border:none;\n"
"border-top:1px solid rgb(92,93,93);\n"
"")
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionopen_video = QtWidgets.QAction(MainWindow)
        self.actionopen_video.setObjectName("actionopen_video")
        self.actionopen_camera = QtWidgets.QAction(MainWindow)
        self.actionopen_camera.setObjectName("actionopen_camera")
        self.actionVersion = QtWidgets.QAction(MainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.action_generate = QtWidgets.QAction(MainWindow)
        self.action_generate.setObjectName("action_generate")
        self.action_setpswd = QtWidgets.QAction(MainWindow)
        self.action_setpswd.setObjectName("action_setpswd")
        self.action_setphone = QtWidgets.QAction(MainWindow)
        self.action_setphone.setObjectName("action_setphone")
        self.action_setemail = QtWidgets.QAction(MainWindow)
        self.action_setemail.setObjectName("action_setemail")
        self.action_setsend = QtWidgets.QAction(MainWindow)
        self.action_setsend.setObjectName("action_setsend")
        self.action_setmodel = QtWidgets.QAction(MainWindow)
        self.action_setmodel.setObjectName("action_setmodel")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionsetargument = QtWidgets.QAction(MainWindow)
        self.actionsetargument.setObjectName("actionsetargument")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionexplain = QtWidgets.QAction(MainWindow)
        self.actionexplain.setObjectName("actionexplain")
        self.action_setmod = QtWidgets.QAction(MainWindow)
        self.action_setmod.setObjectName("action_setmod")
        self.actionApiKey = QtWidgets.QAction(MainWindow)
        self.actionApiKey.setObjectName("actionApiKey")
        self.actionGenerate = QtWidgets.QAction(MainWindow)
        self.actionGenerate.setObjectName("actionGenerate")
        self.actionPreview = QtWidgets.QAction(MainWindow)
        self.actionPreview.setObjectName("actionPreview")
        self.actionSimulate = QtWidgets.QAction(MainWindow)
        self.actionSimulate.setObjectName("actionSimulate")
        self.actionTest = QtWidgets.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.actionMap = QtWidgets.QAction(MainWindow)
        self.actionMap.setObjectName("actionMap")
        self.actionModel = QtWidgets.QAction(MainWindow)
        self.actionModel.setObjectName("actionModel")
        self.menu_F.addAction(self.actionImport)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.actionGenerate)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.actionPreview)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.actionSimulate)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.actionTest)
        self.menu_F.addSeparator()
        self.menu_S_2.addAction(self.actionApiKey)
        self.menu_S_2.addSeparator()
        self.menu_S_2.addAction(self.actionModel)
        self.menu_S_2.addSeparator()
        self.menu_S_2.addAction(self.actionMap)
        self.menu_S_2.addSeparator()
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_S_2.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBoxCarCount.setCurrentIndex(-1)
        self.comboBoxRoadType.setCurrentIndex(-1)
        self.comboBoxV1Direction.setCurrentIndex(-1)
        self.comboBoxV1Lane.setCurrentIndex(-1)
        self.comboBoxLaneCount.setCurrentIndex(-1)
        self.comboBoxV1Action.setCurrentIndex(-1)
        self.comboBoxV1TargetLane.setCurrentIndex(-1)
        self.comboBoxV2Lane.setCurrentIndex(-1)
        self.comboBoxV2TargetLane.setCurrentIndex(-1)
        self.comboBoxV2Action.setCurrentIndex(-1)
        self.comboBoxV2Direction.setCurrentIndex(-1)
        self.comboBoxEgo.setCurrentIndex(-1)
        self.comboBoxWeather.setCurrentIndex(-1)
        self.comboBoxImpactPart.setCurrentIndex(-1)
        self.comboBoxStriker.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "CarCount:"))
        self.label_3.setText(_translate("MainWindow", "RoadType:"))
        self.label_4.setText(_translate("MainWindow", "V1Direction："))
        self.label_5.setText(_translate("MainWindow", "V1Lane："))
        self.label_8.setText(_translate("MainWindow", "LaneCount："))
        self.label_9.setText(_translate("MainWindow", "V1Action："))
        self.label_10.setText(_translate("MainWindow", "V1TargetLane："))
        self.labelV2Lane.setText(_translate("MainWindow", "V2Lane："))
        self.labelV2TargetLane.setText(_translate("MainWindow", "V2TargetLane:"))
        self.labelV2Direction.setText(_translate("MainWindow", "V2Direction："))
        self.labelV2Action.setText(_translate("MainWindow", "V2Action："))
        self.label_11.setText(_translate("MainWindow", "V1Speed："))
        self.labelV2Speed.setText(_translate("MainWindow", "V2Speed："))
        self.label_12.setText(_translate("MainWindow", "EGO："))
        self.label_13.setText(_translate("MainWindow", "Weather："))
        self.label_6.setText(_translate("MainWindow", "Striker:"))
        self.label_7.setText(_translate("MainWindow", "HitPart："))
        self.label_14.setText(_translate("MainWindow", "Report Extract Result"))
        self.label_15.setText(_translate("MainWindow", "Cumulative Accuracy of Accident Information Extraction"))
        self.label_16.setText(_translate("MainWindow", "Crash Information Ground Truth Config"))
        self.label_17.setText(_translate("MainWindow", "Test Case Result"))
        self.label_18.setText(_translate("MainWindow", "Apply To Test Case Generation"))
        self.label_19.setText(_translate("MainWindow", "Add To Record"))
        self.labelCopyInfoGPT.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;color:black\">点击复制结果</span></p></body></html>"))
        self.labelCopyWaypoint.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;color:black\">点击复制结果</span></p></body></html>"))
        self.labelCopyInfoGT.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;color:black\">点击复制配置</span></p></body></html>"))
        self.labelCopyRate.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;color:black\">点击复制准确率</span></p></body></html>"))
        self.menu_F.setTitle(_translate("MainWindow", "File(&F)"))
        self.menu_S_2.setTitle(_translate("MainWindow", "Settings(&S)"))
        self.actionImport.setText(_translate("MainWindow", "Import Report"))
        self.actionImport.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionopen_video.setText(_translate("MainWindow", "打开视频"))
        self.actionopen_video.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionopen_camera.setText(_translate("MainWindow", "打开摄像头"))
        self.actionopen_camera.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionVersion.setText(_translate("MainWindow", "版本"))
        self.actionVersion.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.action_generate.setText(_translate("MainWindow", "生成"))
        self.action_generate.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.action_setpswd.setText(_translate("MainWindow", "修改密码"))
        self.action_setpswd.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_setphone.setText(_translate("MainWindow", "修改手机"))
        self.action_setphone.setShortcut(_translate("MainWindow", "Alt+S"))
        self.action_setemail.setText(_translate("MainWindow", "修改邮箱"))
        self.action_setemail.setShortcut(_translate("MainWindow", "Alt+Y"))
        self.action_setsend.setText(_translate("MainWindow", "推送设置"))
        self.action_setsend.setShortcut(_translate("MainWindow", "Alt+T"))
        self.action_setmodel.setText(_translate("MainWindow", "模型设置"))
        self.action_setmodel.setShortcut(_translate("MainWindow", "Alt+X"))
        self.actionAbout.setText(_translate("MainWindow", "关于"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionsetargument.setText(_translate("MainWindow", "参数设置"))
        self.actionsetargument.setShortcut(_translate("MainWindow", "Alt+C"))
        self.actionHelp.setText(_translate("MainWindow", "帮助"))
        self.actionHelp.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionexplain.setText(_translate("MainWindow", "说明"))
        self.actionexplain.setShortcut(_translate("MainWindow", "Alt+E"))
        self.action_setmod.setText(_translate("MainWindow", "模型设置"))
        self.action_setmod.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionApiKey.setText(_translate("MainWindow", "API Key"))
        self.actionApiKey.setShortcut(_translate("MainWindow", "Ctrl+K"))
        self.actionGenerate.setText(_translate("MainWindow", "Generate Test Case"))
        self.actionGenerate.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.actionPreview.setText(_translate("MainWindow", "Preview Test Case"))
        self.actionPreview.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionSimulate.setText(_translate("MainWindow", "Reconstruction Effect Test"))
        self.actionSimulate.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionTest.setText(_translate("MainWindow", "Simulation Test"))
        self.actionTest.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionMap.setText(_translate("MainWindow", "Map"))
        self.actionMap.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionModel.setText(_translate("MainWindow", "Model"))
        self.actionModel.setShortcut(_translate("MainWindow", "Ctrl+D"))
