# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SetApiKeyPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class SetApiKeyPage(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(585, 284)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 561, 211))
        self.label_4.setStyleSheet("color:rgb(0,0,0);background-color:rgb(231,231,231);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 521, 41))
        self.widget.setStyleSheet("background-color:rgb(125,182,191);\n"
"border:none;")
        self.widget.setObjectName("widget")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 171, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(0,0,0);")
        self.label_5.setObjectName("label_5")
        self.pushButtonSetNewKey = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSetNewKey.setGeometry(QtCore.QRect(440, 170, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButtonSetNewKey.setFont(font)
        self.pushButtonSetNewKey.setStyleSheet("QPushButton{\n"
"    background-color: rgb(20, 136, 208);\n"
"    border-radius:5px;\n"
"    color:rgb(236, 236, 236);\n"
"}\n"
"QPushButton::pressed{\n"
"    border:2px solid rgb(236, 236, 236);\n"
"}")
        self.pushButtonSetNewKey.setObjectName("pushButtonSetNewKey")
        self.lineEditNewKey = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNewKey.setGeometry(QtCore.QRect(110, 100, 441, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lineEditNewKey.setFont(font)
        self.lineEditNewKey.setStyleSheet("\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lineEditNewKey.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEditNewKey.setObjectName("lineEditNewKey")
        self.pushButtonClose = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonClose.setGeometry(QtCore.QRect(530, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClose.setFont(font)
        self.pushButtonClose.setStyleSheet("QPushButton{\n"
"color:white;\n"
"    background-color:rgb(125,182,191);\n"
"border:none\n"
"}\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: rgb(233,16,34);\n"
"}")
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 100, 71, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Settings &gt; API Key</span></p></body></html>"))
        self.pushButtonSetNewKey.setText(_translate("MainWindow", "OK"))
        self.pushButtonClose.setText(_translate("MainWindow", "×"))
        self.label.setText(_translate("MainWindow", "API Key:"))
