# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SetModelPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class SetModelPage(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 284)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 71, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 541, 211))
        self.label_4.setStyleSheet("background-color:rgb(231,231,231)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 501, 41))
        self.widget.setStyleSheet("background-color:rgb(125,182,191);\n"
"border:none;")
        self.widget.setObjectName("widget")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 161, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(0,0,0);")
        self.label_5.setObjectName("label_5")
        self.pushButtonSetNewModel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSetNewModel.setGeometry(QtCore.QRect(420, 170, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.pushButtonSetNewModel.setFont(font)
        self.pushButtonSetNewModel.setStyleSheet("QPushButton{\n"
"    background-color: rgb(20, 136, 208);\n"
"    border-radius:5px;\n"
"    color:rgb(236, 236, 236);\n"
"}\n"
"QPushButton::pressed{\n"
"    border:2px solid rgb(236, 236, 236);\n"
"}")
        self.pushButtonSetNewModel.setObjectName("pushButtonSetNewModel")
        self.pushButtonClose = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonClose.setGeometry(QtCore.QRect(510, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClose.setFont(font)
        self.pushButtonClose.setStyleSheet("QPushButton{\n"
"color:white;\n"
"    background-color:rgb(125,182,191);\n"
"border:none\n"
"}\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: rgb(233,16,34);\n"
"}")
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.comboBoxModel = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxModel.setGeometry(QtCore.QRect(100, 100, 431, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBoxModel.setFont(font)
        self.comboBoxModel.setStyleSheet("QComboBox{\n"
"    background-color:rgb(236,236,236);\n"
"    color:rgb(0, 0 ,0);\n"
"    border:1px solid rgb(190, 190, 190);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray; \n"
"    color: rgb(0, 0, 0);\n"
"   background-color: rgb(236,236,236);    \n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: rgb(236,236,236);\n"
"    background-color: rgb(20, 136, 208); \n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxModel.setObjectName("comboBoxModel")
        self.label_4.raise_()
        self.label_3.raise_()
        self.widget.raise_()
        self.pushButtonSetNewModel.raise_()
        self.pushButtonClose.raise_()
        self.comboBoxModel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 571, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">Model：</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">Settings &gt; Model</span></p></body></html>"))
        self.pushButtonSetNewModel.setText(_translate("MainWindow", "OK"))
        self.pushButtonClose.setText(_translate("MainWindow", "×"))
